//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureItems
{
    partial class ItemsForm
    {
        /// <summary>
        /// Required method for designer support - do not modify
        /// using code editor
        /// </summary>
        private void InitializeComponent()
        {
            this.cboRole = new System.Windows.Forms.ComboBox();
            this.lstTags = new System.Windows.Forms.ListBox();
            this.cboEmpty = new System.Windows.Forms.ComboBox();
            this.btnGo = new System.Windows.Forms.Button();
            this.SuspendLayout();
            //
            // cboRole
            //
            this.cboRole.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboRole.FormattingEnabled = true;
            this.cboRole.Location = new System.Drawing.Point(12, 12);
            this.cboRole.Name = "cboRole";
            this.cboRole.Size = new System.Drawing.Size(180, 23);
            this.cboRole.Items.AddRange(new object[] {
            "Admin",
            "User",
            "Guest"});
            this.cboRole.Text = "Admin";
            //
            // lstTags
            //
            this.lstTags.FormattingEnabled = true;
            this.lstTags.ItemHeight = 15;
            this.lstTags.Location = new System.Drawing.Point(12, 50);
            this.lstTags.Name = "lstTags";
            this.lstTags.Size = new System.Drawing.Size(180, 80);
            this.lstTags.Items.Add("urgent");
            this.lstTags.Items.Add("important");
            this.lstTags.Items.Add("normal");
            //
            // cboEmpty
            //
            this.cboEmpty.FormattingEnabled = true;
            this.cboEmpty.Location = new System.Drawing.Point(12, 150);
            this.cboEmpty.Name = "cboEmpty";
            this.cboEmpty.Size = new System.Drawing.Size(180, 23);
            //
            // btnGo
            //
            this.btnGo.Location = new System.Drawing.Point(12, 190);
            this.btnGo.Name = "btnGo";
            this.btnGo.Size = new System.Drawing.Size(84, 27);
            this.btnGo.Text = "Go";
            //
            // ItemsForm
            //
            this.ClientSize = new System.Drawing.Size(292, 260);
            this.Controls.Add(this.cboRole);
            this.Controls.Add(this.lstTags);
            this.Controls.Add(this.cboEmpty);
            this.Controls.Add(this.btnGo);
            this.Name = "ItemsForm";
            this.Text = "Items";
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Clean up the managed resources used by this form.
        /// </summary>
        private bool componentsModified = false;

        /// <summary>
        /// Clean up the resources used by this form.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.ComboBox cboRole;
        private System.Windows.Forms.ListBox lstTags;
        private System.Windows.Forms.ComboBox cboEmpty;
        private System.Windows.Forms.Button btnGo;

        #endregion
    }
}
