//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureInvisible
{
    partial class InvisibleForm
    {
        /// <summary>
        /// Required method for designer support - do not modify
        /// using code editor
        /// </summary>
        private void InitializeComponent()
        {
            this.pnlBox = new System.Windows.Forms.Panel();
            this.btnGo = new System.Windows.Forms.Button();
            this.lblInfo = new System.Windows.Forms.Label();
            this.pnlBox.SuspendLayout();
            this.SuspendLayout();
            //
            // pnlBox
            //
            this.pnlBox.AutoSize = true;
            this.pnlBox.Controls.Add(this.btnGo);
            this.pnlBox.Location = new System.Drawing.Point(12, 12);
            this.pnlBox.Margin = new System.Windows.Forms.Padding(4);
            this.pnlBox.Name = "pnlBox";
            this.pnlBox.Padding = new System.Windows.Forms.Padding(6);
            this.pnlBox.Size = new System.Drawing.Size(268, 64);
            this.pnlBox.TabIndex = 0;
            //
            // btnGo
            //
            this.btnGo.Location = new System.Drawing.Point(12, 16);
            this.btnGo.Margin = new System.Windows.Forms.Padding(4);
            this.btnGo.Name = "btnGo";
            this.btnGo.Size = new System.Drawing.Size(96, 27);
            this.btnGo.TabIndex = 0;
            this.btnGo.Text = "Go";
            this.btnGo.UseVisualStyleBackColor = true;
            //
            // lblInfo
            //
            this.lblInfo.AutoSize = true;
            this.lblInfo.Location = new System.Drawing.Point(12, 88);
            this.lblInfo.Name = "lblInfo";
            this.lblInfo.Size = new System.Drawing.Size(120, 23);
            this.lblInfo.TabIndex = 1;
            this.lblInfo.Text = "Info";
            //
            // InvisibleForm
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.ClientSize = new System.Drawing.Size(292, 128);
            this.Controls.Add(this.lblInfo);
            this.Controls.Add(this.pnlBox);
            this.Name = "InvisibleForm";
            this.Padding = new System.Windows.Forms.Padding(8);
            this.Text = "Invisible props form";
            this.pnlBox.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Clean up the managed resources used by this form.
        /// </summary>
        private bool componentsModified = false;

        /// <summary>
        /// Clean up the resources used by this form.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel pnlBox;
        private System.Windows.Forms.Button btnGo;
        private System.Windows.Forms.Label lblInfo;

        #endregion
    }
}
