//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixtureLocalizable
{
    partial class LocalizableForm
    {
        /// <summary>
        /// Required method for designer support - do not modify
        /// using code editor
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.pnlToolbar = new System.Windows.Forms.Panel();
            this.ThirdPartyGauge = new ThirdParty.Widgets.GaugeControl();
            this.txtSearch = new System.Windows.Forms.TextBox();
            this.btnGo = new System.Windows.Forms.Button();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LocalizableForm));
            this.pnlToolbar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.txtSearch)).BeginInit();
            this.SuspendLayout();
            //
            // pnlToolbar
            //
            this.pnlToolbar.Controls.Add(this.ThirdPartyGauge);
            this.pnlToolbar.Controls.Add(this.txtSearch);
            this.pnlToolbar.Controls.Add(this.btnGo);
            this.pnlToolbar.Location = new System.Drawing.Point(12, 12);
            this.pnlToolbar.Name = "pnlToolbar";
            this.pnlToolbar.Size = new System.Drawing.Size(400, 44);
            this.pnlToolbar.TabIndex = 0;
            //
            // ThirdPartyGauge
            //
            this.ThirdPartyGauge.Location = new System.Drawing.Point(312, 8);
            this.ThirdPartyGauge.Name = "ThirdPartyGauge";
            this.ThirdPartyGauge.Size = new System.Drawing.Size(80, 28);
            this.ThirdPartyGauge.TabIndex = 2;
            this.ThirdPartyGauge.GaugeMaximum = 100;
            this.ThirdPartyGauge.GaugeSegments = 10;
            //
            // txtSearch
            //
            this.txtSearch.Location = new System.Drawing.Point(4, 10);
            this.txtSearch.Name = "txtSearch";
            this.txtSearch.Size = new System.Drawing.Size(220, 23);
            this.txtSearch.TabIndex = 0;
            //
            // btnGo
            //
            this.btnGo.Location = new System.Drawing.Point(232, 9);
            this.btnGo.Name = "btnGo";
            this.btnGo.Size = new System.Drawing.Size(72, 25);
            this.btnGo.TabIndex = 1;
            this.btnGo.Text = "Go";
            this.btnGo.UseVisualStyleBackColor = true;
            //
            // LocalizableForm
            //
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            resources.ApplyResources(this.txtSearch, "txtSearch.Text");
            resources.ApplyResources(this.btnGo, "btnGo.Text");
            resources.ApplyResources(this, "$this.Text");
            this.ClientSize = new System.Drawing.Size(424, 240);
            this.Controls.Add(this.pnlToolbar);
            this.Name = "LocalizableForm";
            this.Text = "Search";
            ((System.ComponentModel.ISupportInitialize)(this.txtSearch)).EndInit();
            this.pnlToolbar.ResumeLayout(false);
            this.pnlToolbar.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Clean up the managed resources used by this form.
        /// </summary>
        private bool componentsModified = false;

        /// <summary>
        /// Clean up the resources used by this form.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
                this.components = null;
            }
            base.Dispose(disposing);
        }

        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel pnlToolbar;
        private ThirdParty.Widgets.GaugeControl ThirdPartyGauge;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.Button btnGo;

        #endregion
    }
}